- bin/citgm
- bin/citgm-dockerify
- lib/citgm.js
- lib/lookup.json
- package.json
- test/test.js
- test/test2-dir/package.json
* Bump version to 0.0.17
* Remove lodash custom script from lookup table
(lodash just checked in npm test support in github)
* Verify that package.json exists before attempting to test
* Verify that npm test is supported before attempting to
test, notify user if it's not and abort
* Add test case for checking lack of npm test
> Multiple updates

- README.md
- SIGNED.md
- bin/citgm
- bin/citgm-dockerify
- lib/update.js
- man/citgm-dockerify.1
- man/citgm.1
- package.json
> Bumping for first minor release

- lib/npm/fetch-script.js
small changes to fetch script to make it easier to read and avoid re requiring variables
> cleanup: move requires out of function

- bin/citgm-all
Some tweaks to the generated markdown. Looks a bunch nicer.
I took the liberty of adding some emoji... we can drop that commit if people are apposed.
🎉🎉🎉🎉🎉🎉
> Imrpove markdown

- lib/lookup.json
* change react to flakey
- will not install on v5
* remove moment
- expects global install of grunt-cli to work
- pr sent upstream to fix
/cc @jasnell @rvagg
> lookup: update modules

- lib/lookup.json
> lookup: switch socket.io to flakey

- bin/citgm-all
- lib/lookup.json
> meta: whoops I spelt flaky wrong

- lib/lookup.json
details can be found in #52. TLDR npm install is not resolving all deps
/cc @jasnell @rvagg
> lookup: mark torrent-stream flaky

- lib/lookup.json
No longer flaky. Comes with grunt-cli as a dev dep
Closes #42
> lookup: bring back moment

- lib/lookup.json
no longer flaky!
Closes #61 
/cc @jasnell @rvagg
> Revert "lookup: mark lodash as flaky"

- known/lodash/lookup.json
- known/lodash/test.js
cleanup various files no longer supported
> meta: remove un-used files

- lib/temp-directory.js
> tmpdir: code refactor

- lib/citgm.js
- lib/npm/index.js
- lib/npm/install.js
- test/test-npm-install.js
This has been bugging me for a while.
/cc @jasnell
> meta: rename npm.setup to npm.install

- lib/npm/install.js
citgm: https://ci.nodejs.org/job/thealphanerd-smoker/159/
> npm: always log the output of npm.install.stdout

- .travis.yml
- README.md
> meta: add .travis.yml

- package.json
A bunch of our deps our out of date
After this commit they will be no-longer
> meta: update npm deps

- lib/reporter/util.js
the sanitizer has the possiblitiy of stringifying undefined, filter that out
> reporter: filter undefined if stringified

- lib/lookup.json
add node-serialport to the lookup
/cc @reconbot
> lookup: add node-serialport

- lib/lookup.json
a few more small modules worth testing
> lookup: add more top modules

- test/npm/test-npm-install.js
- test/npm/test-npm-script-fetch.js
- test/npm/test-npm-script-run.js
- test/npm/test-npm-test.js
- test/reporter/test-reporter-tap.js
- test/test-citgm.js
- test/test-create-options.js
- test/test-grab-module-data.js
- test/test-grab-project.js
- test/test-lookup.js
- test/test-unpack.js
Change to match the documented api rather than an undocumented alias
/cc @samgithub
> test: change t.done instances to t.end

- bin/citgm-all.js
- lib/citgm.js
- lib/lookup.js
- test/bin/test-citgm-all.js
- test/fixtures/custom-lookup-flaky.json
I don't know how this ever worked.
> citgm: fix flaky

- lib/lookup.json
this should likely already be in there.
> lookup: add graceful-fs

- lib/lookup.json
add more native modules as suggested in #162
> lookup: add native modules

- bin/citgm.js
The switch the yargs broke this
> bin: when no argument is passed to -t or -x print

- bin/citgm-all.js
- test/bin/test-citgm-all.js
- test/fixtures/custom-lookup-broken.json
This if statement seems to catch any errors (if the json file is broken or doesn't exist)
> add a custom json file check

- lib/lookup.json
Current release and master are broken. Skipping
> lookup: skip ember-cli

- package.json
This is being included in both deps and dev-deps
> chore: do not double declare eslint

- lib/lookup.json
React is now developing using yarn, build is unreliable
Skip until we have a better idea of what to do
> lookup: skip react

- lib/lookup.json
> lookup: skip yargs

- lib/lookup.json
Test suite does not support v8
> lookup: skip eslint on v8

- lib/lookup.json
Build is currently broken
```
Error: Cannot find module 'cliui'
```
Will investigate
> lookup: skip uglify-js

- lib/npm/install.js
> log: add missing space between name and nodedir

- man/citgm-all.1
- man/citgm.1
> man: update manual for citgm and citgm-all

- lib/lookup.json
a few more modules should fail on fips
> lookup: mark more fips failures as expectFail

- README.md
- bin/citgm-all.js
- bin/citgm.js
- lib/common-args.js
- lib/npm/install.js
- lib/temp-directory.js
- man/citgm-all.1
- man/citgm.1
- test/test-temp-directory.js
This PR allows you to pass in `citgm-all --tmpDir /path/to/directory`
> bin: allow custom test path to be used

- lib/lookup.json
Updated flaky/skip tags for AIX
> lookup: updated skip/flaky tags for AIX

- lib/lookup.json
adding a few flaky tags, mainly on rhel
> lookup: update flaky tags

- package.json
> deps: update Tap to 10.1.0

- RELEASES.md
This is a rough first pass. Comments and suggestions welcome :D
> doc: create release guide

- .eslintrc.yml
We should really be supporting es6 rules. If there are any changes we want to make (e.g. something from [the core .eslintrc.yaml](https://github.com/nodejs/node/blob/master/.eslintrc.yaml) then we could add that as well.
> eslint: support es6 rules

- lib/lookup.json
> lookup: unskip david

- README.md
- lib/lookup.json
closes: https://github.com/nodejs/citgm/issues/359
> lookup: add metadata on who to ping

- .jshintrc
as far as I can tell we don't actually need this file anymore
> remove .jshintrc

- .github/PULL_REQUEST_TEMPLATE.md
we currently have the these checklist items in the PR template:
commit message follows commit guidelines is not really necessary as
the contributing guidelines already cover the commit guidelines
> doc: remove item from PR checklist

- package.json
> deps: update yargs to 7.0.1

- README.md
- lib/common-args.js
- man/citgm-all.1
- man/citgm.1
> logger: add --loglevel as an alias to --verbose

- CONTRIBUTING.md
- README.md
This PR moves the module submission requirements from README.md to
CONTRIBUTING.md
> doc: move module submission requirements

- lib/lookup.json
this module is used across the ecosystem for working with ASTs
Around 1 million downloads a day
> lookup: add acorn and esprima

- lib/lookup.json
closes: https://github.com/nodejs/citgm/issues/432
> lookup: fixup flaky modules

- lib/lookup.json
same issue as https://github.com/nodejs/citgm/pull/424
> lookup: skip zeromq on ppc

- lib/unpack.js
- package.json
In this new version, the "path" option was replaced by "cwd" and it
appears that the directory is no longer automatically created.
> deps: update tar to v3.1.5

- lib/lookup.json
currently failing :(
Refs: https://github.com/nodejs/citgm/issues/467
> lookup: skip yeoman on 8.x and higher

- lib/lookup.json
Test suite currently broken
Refs: https://github.com/nodejs/citgm/issues/466
> lookup: skip ftp on Node >= 8

- lib/lookup.json
Fixes: https://github.com/nodejs/citgm/issues/467
> lookup: unskip yeoman-generator on 8.x

- lib/lookup.json
Closes: https://github.com/nodejs/citgm/issues/480
> lookup: s/coffee-script/coffeescript

- lib/lookup.json
> lookup: skip shot on <8

- lib/lookup.json
> lookup: skip radium on v4.x

- lib/lookup.json
Compatibility with node >= 9 fixed.
/CC @srl295
> lookup: unskip icu-full-test >= 9.x

- package.json
Fixes: https://github.com/nodejs/citgm/issues/525
> chore: update tar 4.0.2 -> 4.1.1

- lib/lookup.json
> lookup: actually skip mocha

- lib/lookup.json
> lookup: [linter] remove extra spacing

- lib/lookup.json
Added to the https://github.com/nodejs/citgm/projects/1.
Refs: https://github.com/nodejs/citgm/pull/544, https://github.com/zeromq/zeromq.js/issues/231
> lookup: skip zeromq on win

- lib/lookup.json
There is a open issue in weak since February and there was no
reaction so far.
Refs: https://github.com/TooTallNate/node-weak/issues/87
Refs: #558
> lookup: skip weak in Node.js > 10

- lib/lookup.json
> lookup: remove unsupported Node.js versions

- lib/lookup.json
> lookup: true isn't a string

- lib/lookup.json
The module  tests pass on Windows
> lookup: unflaky spawn-wrap on win32

- lib/lookup.json
The test suite for this module is passing
> lookup: unskip uglify-js on Windows

- lib/lookup.json
`coffeescript` tests pass on Windows
> lookup: unskip coffeescript

- lib/lookup.json
Recently clinic-flame broke in multiple minor releases. This should
protect against it / detect such breaking changes early.
* Module source code must be on Github. :heavy_check_mark: 
* Published versions must include a tag on Github :heavy_check_mark: 
* The test process must be executable with only the commands
`npm install && npm test` using the tarball downloaded from the Github tag
mentioned above :heavy_check_mark: 
* The tests pass on supported major release lines :heavy_check_mark: 
* The maintainers of the module remain responsive when there are problems :heavy_check_mark: 
* At least one module maintainer must be added to the lookup maintainers field :heavy_check_mark: 
At least one of:
* The module must be actively used by the community :heavy_check_mark: 
OR
* The module must …
> Add clinic suite

- lib/lookup.json
Fails consistently on 8.x and 6.x
/cc @mcollina @bridgear
> lookup: skip @nearform/flame <8

- lib/lookup.json
Test suite is broken and failing on all versions of node
/cc @mcollina @BridgeAR
> lookup: skip @nearform/flame

- lib/lookup.json
> lookup: set bubbleprof to flaky

- lib/lookup.json
Refs: https://github.com/nearform/node-clinic-doctor/issues/192
> lookup: skip doctor on ubuntu and debian

- test/fixtures/fakenodebin/fake-node.bat
Create a fake-node.bat file that can be found by the which module and
executed on Windows.
/cc @bzoz 
> test: fix tests with fake node-bin on Windows

- .gitattributes
The tests assume the sources where check-out with LF line endings.
> tools: make Windows use LF on checkout

- lib/lookup.json
- test/test-lookup.js
Fixes: https://github.com/nodejs/citgm/issues/644
> lookup: sort the lookup table alphabetically

- lib/lookup.json
There have been changes to the Doctor and Flame tests but we're not sure
that they're now fully stable on CITGM. Mark them as flaky so they at
least run and we can check the output if they still fail.
> lookup: mark @nearform/doctor and flame flaky

- lib/lookup.json
> lookup: skip clinic <6

- lib/lookup.json
Consistently getting weird failures on various platforms
in different ways. This is something we should prioritize fixing.
> lookup: skip bluebird

- lib/lookup.json
> fix lookup

- lib/lookup.json
Microtime was updated to the latest version of nan, and an n-api version will be released soon.
https://github.com/wadey/node-microtime/issues/61
> don't skip 12 for microtime

- bin/citgm-all.js
Replace lodash _reduce() with Array.prototype.map().
Remove unused argument to launch().
> bin: refactor citgm-all

- lib/lookup.json
node-report@2.2.4 and nan@2.13.0 build successfully against Node.js 12.
> lookup: unskip node-report for Node.js 12

- lib/lookup.json
> lookup: update maintainers of level(down)

- bin/citgm-all.js
- lib/lookup.json
Compatible with Node 12 since v3.0.4
> lookup: don't skip bcrypt for v12

- lib/lookup.json
- package-lock.json
something has changed under the hood and cheerio is failing in CITGM
This is specific to the citgm runtime and I was unable to bisect the
issue. Skipping for now and will make a tracking issue.
> lookup: skip cheerio

- .npmignore
- package.json
> package: use explicit files list instead of .npmignore

- .travis.yml
- lib/spawn.js
- package.json
- test/test-spawn.js
> travis: test on Windows

- lib/create-options.js
- lib/lookup.json
- test/test-create-options.js
Fixes: https://github.com/nodejs/citgm/issues/737
> fix: always set the YARN_IGNORE_ENGINES env variable

- lib/lookup.json
Based on local testing (Linux)
> lookup: unskip and unflaky some modules

- .travis.yml
> chore: update Node.js versions tested on Travis

- .travis.yml
Fixes: https://github.com/nodejs/citgm/issues/747
> travis: add git directories to PATH for Windows

- .github/workflows/nodejs.yml
- .travis.yml
> chore: add GitHub action to run tests

- lib/lookup.json
> lookup: update based on v13.2.0 tests

- lib/lookup.json
Ava is timing out for install on almost every platform
Coffeescript is failing on rhel
acorn is failing on install (timeout) on ppc
> Update dec 2

- .github/workflows/nodejs.yml
> tools: drop v13.x from actions

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/nodejs.yml
- COLLABORATORS.md
- CONTRIBUTING.md
- LICENSE.md
- RELEASES.md
s/master/main where is made sense
> doc: update outdated references to master branch

- lib/grab-module-data.js
- lib/grab-project.js
* move silly logging of full meta data to right after retrieval
* convert lifecycle logs of fetching metadata from silly to verbose
> lib: improve logging of package metadata

- lib/lookup.json
Refs: https://github.com/nodejs/citgm/pull/827#issuecomment-696813496
cc @cjihrig 
> lookup: replace shot with @hapi/shot

- lib/lookup.json
Adding [undici](https://github.com/nodejs/undici).
> Added undici to lookup.json

- .github/workflows/nodejs.yml
> ci: update actions/setup-node to v2 and refine entire workflow

- CONTRIBUTING.md
- lib/lookup.json
Fixes: https://github.com/nodejs/citgm/issues/838
Unskip Commander after fixing issue in Commander with space in path (and before that some unreliability).
Changed maintainer to the active maintainers, and fixed a spelling mistake as a bonus.
**Hard Requirements**
**Soft Requirements**
At least one of:
> lookup: unskip commander

- CODE_OF_CONDUCT.md
- ModerationPolicy.md
- README.md
- RELEASES.md
- Use HEAD for links
- Use main for local references
> doc: replace master with main/HEAD

- lib/lookup.json
> lookup: add missing "v" prefix to undici

- lib/lookup.json
> lookup: rm hyphen from debian ref for hapi

- test/bin/test-citgm-all.js
Refs: https://github.com/nodejs/citgm/issues/879
> test: fix test-citgm-all on Windows

- lib/grab-project.js
- lib/lookup.json
- package.json
- fix: properly download package tarballs
- lookup: skip pug if >=16
> Fix tarball downloads

- package.json
Resolves a critical warning on npm install.
> chore: update tap and tap-parser

- lib/lookup.json
Installation of `yargs` appears to require npm 8 to succeed. Skip
for Node.js which includes npm 6.
Remove flaky designation for ppc as the tests appear to be passing.
---
CI for yargs (including failures on Node.js 14): https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-pipeline/174/
Example failure with npm 6:
https://ci.nodejs.org/job/citgm-smoker-nobuild/nodes=ubuntu1804-64/1292/testReport/junit/(root)/citgm/yargs_v17_5_1/
```
> yargs@17.5.1 prepare /home/iojs/tmp/citgm_tmp/a5532b74-b2b3-4d0f-8e57-0bccb70030cc/yargs
> npm run compile
> yargs@17.5.1 compile /home/iojs/tmp/citgm_tmp/a5532b74-b2b3-4d0f-8e57-0bccb70030cc/yargs
> rimraf build && tsc
> yargs@17.5.1 postcompile /home/iojs/tmp/citgm_tmp/a5532b74-b2b3-4d0f-8e57-0bccb70030cc/yargs
> npm run build:cjs
> yargs@17.5.1 …
```
> lookup: skip yargs on Node.js 14

- lib/lookup.json
All good on s390x in nodejs 14, 16, 18
> Unskipping cheerio on s390x

- lib/lookup.json
> lookup: skip mkdirp

- lib/lookup.json
This PR adds `lru-cache` module on `/lib/lookup.json`
At least one of:
> lookup: add lru-cache

- README.md
Refs: https://github.com/nodejs/Release/pull/833
> doc: move team list from nodejs/release

- .github/workflows/test-module.yml
- package.json
> chore: Replace EOL Node 14/19 with Node 20

- lib/lookup.json
Ref: https://github.com/nodejs/citgm/pull/959#issuecomment-1712071728
> lookup: remove async from test suite

- lib/lookup.json
Ref: https://github.com/nodejs/citgm/pull/959#discussion_r1319157550
> lookup: remove spawn-wrap from test suite

- package.json
Remove -J to improve reliability of GitHub Actions results.
> chore: improve stability of tests

- README.md
> doc: fix build status badge

- lib/lookup.json
Refs: https://github.com/nodejs/node/pull/51043#issuecomment-1838742464
> lookup: use HEAD for `inherits`

- .github/workflows/close-stalled.yml
I belive it should help a bit to manage ongoing conversations.
> workflow: add close-stalled workflow

- lib/lookup.json
See: https://github.com/cheeriojs/cheerio/blob/main/package.json#L96
> lookup: update cheerio test command

- .github/workflows/nodejs.yml
- .github/workflows/test-module.yml
- .npmrc
- .prettierignore
- npm-shrinkwrap.json
- package.json
Refs: https://github.com/nodejs/node-core-utils/pull/976
Refs: https://github.com/nodejs/node-core-utils/pull/975
> fix(package): pin dependencies and disable install scripts
