README.md
SIGNED.md
bin/citgm
bin/citgm-dockerify
lib/citgm.js
package.json

The `-d` or `--nodedir` command line flags can now be used to set the `--nodedir` option 
during npm install. 
Note: when using citgm-dockerify, you *must* have a `nodedir` folder containing the node src
located in your local working directory before building the image. This is because docker will 
refuse to copy the node src image if it's not local to the working directory and citgm's npm install
in the docker file won't be able to find it either. This is temporary. An alternative solution is being
worked on.
The `-c` or `--citgmdir` command line flag has been added to citgm-dockerify to specify the local
path to citgm. When specified, the docker image will install citgm from the specified location rather
than using npm.

Add support for --nodedir and --citgmdir

---

README.md
bin/citgm
bin/citgm-all
lib/citgm.js
lib/lookup.js
lib/lookup.json
man/citgm-all.1
package.json
test/fixtures/custom-lookup-fail.json
test/fixtures/custom-lookup-skip.json
test/fixtures/custom-lookup.json
test/fixtures/pretty-print.json
test/test-citgm-all.js
test/test-lookup.js

This PR adds a new bin to the project ```citgm-all```
By default ```citgm-all``` will run the test suite of every package in the lookup table. If a custom lookup table is provided it will iterate across that instead.
TODO:

bin: add citgm-all

---

lib/lookup.json

as documented in #47 request is being flaky on certain systems. This changes the flag to make CI pass for now

lookup: label request flaky

---

bin/citgm-all

A run of citgm-all should not fail if npm fails to fetch a module.

citgm-all:  if npm fails to fetch mark flaky

---

lib/lookup.json

Lodash v4.0.0 is missing files from the tar ball that is
causing citgm to fail.
This is being tracked in #61

lookup: mark lodash as flaky

---

bin/citgm
bin/citgm-all

Just noticed we are not dynamically getting the version number.
I noticed as the version is currently 0.2.x... whoops
Let's never make this mistake again!
/cc @jasnell @rvagg

bin: get version from package.json

---

bin/citgm

this was missed in the deprecation of scripts / hmac
/cc @jasnell

bin: remove option for test in citgm

---

lib/lookup.json

Jade has recently switched orgs to pugjs, but the package.json does not reflect this
As such our resolving algorithm for tarballs is borking.
Manually specify repo until they update the package.json upstream
/cc @jasnell @Fishrock123 @nodejs/smoke-test

lookup: explicitly state jade repo

---

lib/lookup.json

this module is often used.
ci for v5.x: https://ci.nodejs.org/job/thealphanerd-smoker/64/
ci for v4.x: https://ci.nodejs.org/job/thealphanerd-smoker/65/
Both appear green!

lookup: add ws

---

lib/lookup.json

this commit adds the following packages to the lookup
* vinyl
* vinyl-fs
* readable-stream
* ftp
* split2
* throughv
* duplexer2
* bl
* binary-csv
* spdy
* dicer
* spdy-transport
* sax
* duplexify
* pumpify
* from2
* flush-write-stream
* jsonstream
* csv-parser
Please feel free to submit more ideas and I'll add them to the list if they work. If they don't, we'll try and get them to :smile: 
/cc @jasnell @chrisdickinson @phated @nodejs/streams

lookup: add packages that test streams

---

README.md
bin/citgm
bin/citgm-all
lib/npm/setup.js
lib/npm/test.js
man/citgm-all.1
man/citgm.1

You can now pass a verbosity level to npm. Data!
Closes #56

 	bin: add --npm-loglevel flag

---

lib/lookup.json

v2.2.0 introduced a regression in the test suite. Will roll back once eslint releases a working version.

lookup: eslint now installing via master

---

.eslintrc
README.md
bin/citgm
bin/citgm-all
lib/citgm.js
lib/lookup.js
lib/lookup.json
lib/npm/test.js
lib/out.js
lib/reporter/index.js
lib/reporter/logger.js
lib/reporter/markdown.js
lib/reporter/tap.js
lib/reporter/util.js
man/citgm-all.1
man/citgm.1
package.json
test/fixtures/custom-lookup-fail.json
test/fixtures/reporter-util-fixtures.json
test/fixtures/test-out-failing.txt
test/fixtures/test-out-passing.txt
test/test-reporter-util.js
test/test-reporter.js
test/test-tap-reporter.js

This is a first pass at adding a tap-reporter to citgm. The reporter is exposes through a command line flag `-t <filepath>`, where if the optional file path is not provided it simply logs directly to STDOUT.
In order to support this reporter there has been a refactor of the general post process reporting that we have done. Outputting the results via the default logger, markdown, or tap are now all sharing the same basic abstraction for the most part.
This has yet to be tested in CI, but it should in theory allow us to start looking at tap output for a basic idea of the results of a run.
Other than the basic error propagated by citgm there is no additional information currently included. I think this is something we can try to improve in a future iteration, if we can find a better way of …

Add tap reporter

---

lib/citgm.js

A small change to the way events is used allows us to supoprt
v0.10.

citgm: fix for v0.10 support 

---

README.md
bin/citgm
lib/npm/script/fetch.js
lib/npm/script/index.js
lib/npm/script/run.js
lib/npm/test.js
man/citgm.1
test/fixtures/custom-lookup-script.json
test/fixtures/example-test-script-failing.sh
test/fixtures/example-test-script-passing.sh
test/fixtures/request-mock.js
test/test-npm-script-fetch.js
test/test-npm-script-run.js

This pr adds back to feature that allows CITGM to be given an
optional second argument that specifies a file path or link to an
alternative script to be run for testing.
This feature also supports a new option in the manifest "script",
which will allow individuals to specify custom scripts to be used
whenever a module is run (including with citgm-all)
This patch is coming in fully testing with close to 100% coverage.
Currently sitting around 90% on average
There is currently quite a bit of overlap between `lib/npm/test`
and `lib/npm/run`, but I think refactoring that would make sense
to happen later, as there is quite a bit of repeated code between
all Child Process stuff, and this could likely be improved.

add custom script support

---

lib/lookup.js
lib/npm/script/fetch.js
test/fixtures/custom-lookup-script.json
test/test-bin.js
test/test-lookup.js
test/test-npm-script-fetch.js

The current logic was only resolving custom scripts relative
to the process. That logic does not really work if you include
a relative path inside of a lookup table.
This fix updates the logic for fetching scripts to resolve paths
found in a lookup table relative to the table if needed
/cc @jasnell

custom-script: fix using custom script in lookup

---

lib/npm/setup.js

This is causing the process in node v5.x to halt.
This is definitely a better approach, but I will investigate the
crash to make sure it isn't a regression in node itself
/cc @jasnell

npm: don't chunk the stderr output of npm install

---

lib/npm/setup.js

Currently we are only logging the output of stderr
If you set the npm logging level higher than error
an extra listener is created.

npm: add stdout output from npm install

---

lib/citgm.js

currently `lib/citgm` adds listeners on the process object for `SIGINT`
`SIGHUP` and `SIGBREAK`. These listeners were not being removed when a
job was completed successfully. This was not a problem at first, but now
that we have citgm-all this created a memory leak.
This commit removes the listeners when the job is successfully completed
/cc @jasnell

fix: remove event listeners on process when done

---

lib/citgm.js
lib/lookup.json
lib/npm/script/run.js
lib/npm/test.js

Currently we are creating giant strings and pushing them through the
eventEmitter. By emitting chunks we can stop the application from
halting at certain times.

npm: do not put big strings through event emitter

---

lib/npm/install.js
test/fixtures/omg-bad-tree/package.json
test/test-npm-install.js

Prior to the code coverage we were checking codes on the exit on npm
install. I was mistaken about the way npm install handles error handling
and had removed the code handling. This brings it back and includes a
test to make sure we do not regress again.
This should solve the CI problems we are having with PPC.

npm: fix install error handling

---

README.md
bin/citgm
bin/citgm-all
lib/npm/install.js
man/citgm-all.1
man/citgm.1
test/test-citgm-sigint.js
test/test-citgm.js
test/test-grab-project.js
test/test-lookup.js
test/test-npm-install.js
test/test-npm-script-fetch.js
test/test-npm-script-run.js
test/test-npm-test.js

We are currently noticing problems in CI with some npm install's
hanging for quite some time. This can make an entire CI run useless.
This PR introduces a new cli options `-o` or `--timeout` which takes
a single argument, a length (of type Number). The default is set to
10 minutes. If an npm install is taking more than 10 minutes it will
simply fail.

npm: introduce timeout for npm install

---

lib/is-flaky.js
lib/lookup.js
lib/lookup.json
package.json
test/test-is-flaky.js

Closes #54 
originally flakyness could only be set as a boolean.
Now it can be set in multiple ways
As a boolean: true | false
As a string: version | platform | arch | platform-arch
e.g 'v5' | 'darwin' | 'x86' | 'darwin-x86'
As an array of targets: ['v5', 'v4', 'x86']
As an object for more granular control:
```
{
'v4': ['darwin', 'arm'],
'v5': true,
'v6': 'linux'
}
```
Or even as an array of objects:
```
[{ 'linux': 'v6' }, {'darwin': ['v4', 'v5', 'v6']}]
```
There is potentially too much granularity here... but it all works
and it is all tested with 100% code coverage so why not.

Granular flake support

---

lib/lookup.json

As of version 1.5.1 of the `body-parser` module, it should no longer be flaky on v6/v7 with updated tests merged from @TheAlphaNerd.

lookup: update body-parser flaky status

---

lib/create-options.js
lib/temp-directory.js
test/test-create-options.js
test/test-npm-script-run.js

Currently npm defaults are causing a leak in $TMPDIR
This change ensures that all the temporary cache for npm is cleaned
by citgm. This will help to fix a problem we noticed in CI of massive
amounts of memory being eaten up over time.
Closes #128

Ensure npm doesn't leave assets in $TMPDIR

---

lib/grab-project.js
lib/npm/install.js
test/test-grab-project.js
test/test-npm-install.js

Add timeout to grab-project and cleanup timeout from `npm.install`
This fixes some breakages and hanging processes we have noticed in CI

Timeout fixes

---

lib/npm/install.js

This reverts commit 0d4ae1c2eb22fe6fe0739bf423e278f10900cafc.
Too many failures, not enough upside
/cc @rvagg

Revert "npm: use --cache-min 999999 when installing"

---

lib/grab-project.js
test/test-grab-project.js

Seems like testing local folders wasn't working, especially for cases
where `npm pack` had a variety of output. This patch sanitizes the output
and ensures the proper module name is propogated

lib: fix local modules

---

lib/lookup.json

Currently this PR adds only `ember-cli` to the citgm lookup table. I think it would also be good to consider other highly depended on + tested repo's that make up the ember ecosystem.
/cc @tomdale @wycats for suggestions
Adding ember.js proper is currently a non starter due to the submodules 😢 
https://github.com/emberjs/ember.js/blob/master/.gitmodules

lookup: add ember-cli

---

README.md
bin/citgm-all.js
bin/citgm.js
lib/common-args.js
package.json

Also cordon off common CLI options into lib/common-args.js to keep
it DRY. This also enables config files and environment variables
as config.
Fixes: #181
Currently this results in two tests failing regarding signal handling, so I'll have to figure that out before removing the `[WIP]`.

bin: use yargs

---

lib/out.js

The ellipsis-wrapping at 50 chars makes it hard to read, hard to copy & paste URLs, etc., so removing that so the lines don't wrap.

logging: remove ellipsis wrapping

---

lib/reporter/util.js
test/fixtures/CR-raw.txt
test/fixtures/CR-sanitized.txt
test/reporter/test-reporter-util.js

Currently we are not sanitizing carriage returns which can break
tap output. This change adds a regular expression to the reporters
sanitizer to replace all carriage returns with new lines.
Fixes: https://github.com/nodejs/citgm/issues/189

reporter: sanitize carriage returns

---

lib/lookup.json

It looks like the tarballs have regressed and are no longer
including the source from the submodules

lookup: skip node-sass

---

bin/citgm.js
lib/common-args.js
test/bin/test-citgm-all.js
test/fixtures/omg-i-pass/package.json

Regression was found while going through coverage. After the switch to
yargs we broke printing tap and junit to stdout.

bin: fix tap / junit output without string

---

.eslintrc
lib/grab-module-data.js

Currently we are not enforcing the use of `===` and `!==` in our linter, we should add this rule

linter: force `===` and `!==`

---

lib/lookup.json

these modules are currently failing in the community ci:
https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/nodes=rhel72-s390x/482/testReport/

lookup: mark failing CI modules as flaky

---

lib/lookup.json

This reverts commit d4ed829891bc73f1a954560892239a5164d61349.

Revert "lookup: skip pug until published version fixed"

---

README.md
lib/lookup.js
lib/lookup.json
test/bin/test-citgm-all.js
test/fixtures/custom-lookup-backwards-compatibilty.json
test/fixtures/custom-lookup-envVar.json
test/fixtures/custom-lookup-fail.json
test/fixtures/custom-lookup-flaky.json
test/fixtures/custom-lookup-install.json
test/fixtures/custom-lookup-no-repo.json
test/fixtures/custom-lookup-script.json
test/fixtures/custom-lookup-skip.json
test/fixtures/custom-lookup.json
test/fixtures/pretty-print.json
test/test-lookup.js

Currently we pass `"replace": true` into our lookup.json file to get the tests from github instead of npm. At the moment all of our modules is lookup.json contain this tag so it makes no sense to make it an option. 
This PR changes makes replace redundant and adds `"npm": true` to NOT get the tests from github and instead get them from npm. This means that existing users with custom json files will still be able to get from npm or github

citgm-all: get modules from github by default

---

package.json

Currently the `npm test` script doesn't work on windows. I have fixed
this and also made it consistent with the way that community runs tests

npm: fix `npm test` script to work on both windows and unix.

---

README.md
bin/citgm-all.js
lib/citgm.js
lib/grab-module-data.js
lib/grab-project.js
lib/lookup.js
lib/npm/install.js
lib/npm/script/fetch.js
lib/npm/script/run.js
lib/npm/test.js
lib/temp-directory.js
lib/unpack.js
test/bin/test-citgm-all.js
test/npm/test-npm-script-fetch.js
test/test-lookup.js
test/test-temp-directory.js

Currently all tests are run one at a time for `citgm-all` are run
sequentially. This is done using async.queue.
It queues to the number of available processors on the system, with a default of 1.

bin: enable parallel task running for citgm-all

---

README.md
lib/citgm.js
lib/lookup.js
lib/reporter/logger.js
lib/reporter/util.js
test/bin/test-citgm-all.js
test/fixtures/custom-lookup-expectFail-fail.json
test/fixtures/custom-lookup-expectFail.json

This PR adds the ability to use `expectFail` in the same way as flaky
but instead will mean that the module MUST fail. Discussed in https://github.com/nodejs/citgm/issues/212

lookup: add expectFail

---

lib/match-conditions.js

Allows you to mark flaky, skip and expectFail as fips
ie `"flaky": "fips"`

flaky: add fips support

---

lib/lookup.json

Add expectFail to all modules that should fail on fips builds

lookup: add expectFail tag to failing fips modules

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

We should have a default issue template and a default PR template. I have briefly drafted one up from the node repository but I am happy to tweak it if people have suggestions

docs: add issue template and PR template

---

lib/lookup.json

libxmljs has been failing on sles and rhel

lookup: mark libxmljs flaky on sles and rhel

---

lib/citgm.js
test/bin/test-citgm.js

change script to be stored in `context.module.script` rather than `context.options.script` for `citgm.js` to be consistent with `citgm-all.js`. This was broken in https://github.com/nodejs/citgm/pull/245

script: change script to be stored in `context.module.script`

---

package.json

some of our dependencies are out of date as shown below:
```
dotenv       ^2.0.0  →   ^4.0.0
eslint      ^2.13.1  →  ^3.13.1
tap          ^8.0.0  →   ^9.0.3
tap-parser   ^3.0.3  →   ^5.1.0
```

chore update dependencies

---

lib/lookup.json

pug is currently failing to install from npm because the tags now contain `pug@` in the prefix. Issue raised: https://github.com/pugjs/pug/issues/2683

lookup: skip pug

---

.eslintrc
bin/citgm-all.js
lib/citgm.js
lib/lookup.js
lib/match-conditions.js
lib/npm/test.js
lib/out.js
lib/unpack.js

linter: enforce a space after commas

---

test/bin/test-citgm.js

currently there are no tests for running citgm with local modules.
The test is designed to run citgm on the locally installed omg-i-pass in the fixtures folder

test: add test for local modules

---

README.md

We should include the usage examples from the manual. This also includes instructions on how to test citgm on a local module

docs: include examples in README.md

---

lib/match-conditions.js
package.json
test/test-match-conditions.js

This PR fixes and issue where dotenv was sometimes returning osRelease
with a parsed key and sometimes without. This meant that pulling the
distro and release version from the object was much harder. I have
swapped dotenv out with a simple regex that only grabs the information
that we need.
Example of the issue:
on rhel and sles x86/x64:
```
{ parsed: 
{ NAME: 'Red Hat Enterprise Linux Server',
VERSION: '7.1 (Maipo)',
ID: 'rhel',
ID_LIKE: 'fedora',
VERSION_ID: '7.1',
PRETTY_NAME: 'Red Hat Enterprise Linux Server 7.1 (Maipo)',
ANSI_COLOR: '0;31',
CPE_NAME: 'cpe:/o:redhat:enterprise_linux:7.1:GA:server',
HOME_URL: 'https://www.redhat.com/',
BUG_REPORT_URL: 'https://bugzilla.redhat.com/',
REDHAT_BUGZILLA_PRODUCT: 'Red Hat Enterprise Linux 7',
REDHAT_BUGZILLA_PRODUCT_VERSION: '7.1', …
```

match conditions: fix for rhel and sles x64/x86

---

.eslintrc.yml
bin/citgm-all.js
bin/citgm.js
lib/citgm.js
lib/grab-module-data.js
lib/grab-project.js
lib/lookup.js
lib/match-conditions.js
lib/npm/index.js
lib/npm/install.js
lib/npm/script/fetch.js
lib/npm/script/run.js
lib/npm/test.js
lib/out.js
lib/reporter/index.js
lib/reporter/junit.js
lib/reporter/logger.js
lib/reporter/markdown.js
lib/reporter/tap.js
lib/spawn.js
lib/temp-directory.js
lib/unpack.js
test/npm/test-npm-script-fetch.js
test/reporter/test-reporter-util.js
test/test-lookup.js
test/test-spawn.js

this PR adds some new linter rules that I feel that we should be using
in CitGM:
```
"no-multi-spaces": 2,
"no-useless-escape": 2,
"array-bracket-spacing": [2, "never"],
"brace-style": 2,
"capitalized-comments": 2,
"eol-last": [2, "always"],
"func-call-spacing": [2, "never"],
"semi-spacing": 2,
```

linter: add new linter rules

---

README.md

We should add dependency status badges to the README to help us keep them updated

readme: add dependencies status badges

---

lib/lookup.json

[nodereport](https://github.com/nodejs/nodereport) is a foundation module that we should be testing. It seems to be passing on our IBM machines so looks like it should be okay

add nodereport to lookup.json

---

.github/PULL_REQUEST_TEMPLATE.md

Using ./CONTRIBUTING.md in the PR template resolves to
https://github.com/nodejs/citgm/compare/CONTRIBUTING.md. Use the full path
instead (as is done in Node.js core).
Note that the CONTRIBUTING.md file hasn't yet been added (the PR to add it is
https://github.com/nodejs/citgm/pull/314).
Link to core PR template: https://raw.githubusercontent.com/nodejs/node/master/.github/PULL_REQUEST_TEMPLATE.md

doc: fix the PR template CONTRIBUTING.md link

---

package.json

There is a major version bump because the module removed support for Node.js 0.10 and 0.12

deps: update update-notifier to 2.1.0

---

lib/lookup.json

commander has a repo tag in the lookup but this is not required

lookup: remove repo from commander

---

lib/lookup.json
test/test-lookup.js

Underscore was marked to use the master branch a while ago but this is no longer required

lookup: stop using master branch for underscore

---

lib/lookup.json

uglify-js seems to be passing now and I have also removed the flaky tag
for darwin

lookup: unskip uglify-js

---

test/test-temp-directory.js

one of the tests in test/test-temp-directory creates a temporary
directory called `thisisatest` but this was not getting cleaned up at
the end of the run

test: remove `thisisatest` folder

---

package.json

this commit reverts #350 which dropped support for 0.10 and 0.12 for
update-notifier

revert #350

---

README.md
bin/citgm-all.js
lib/check-tags.js
lib/lookup.js
man/citgm-all.1
test/bin/test-citgm-all.js
test/fixtures/custom-lookup-tags.json
test/test-check-tags.js

this PR adds the functionality to run `citgm-all` on specific tags in
the lookup by passing in the `includeTags` or `excludeTags` option.
fixes https://github.com/nodejs/citgm/issues/72

bin: allow testing subsystems

---

CONTRIBUTING.md

We should have a contributing guidelines file:
Inital Draft, open to ideas

Add a Contributing Guidelines file

---

lib/lookup.json

Continuing from https://github.com/nodejs/citgm/issues/268 - this adds `thread-sleep`, `utf-8-validate`, `bufferutul`, `weak` and `hiredis` to `lookup.json`.

Add modules to lookup.json

---

lib/lookup.json

lookup: fs-extra now has a prefix

---

lib/lookup.json

node-sass and tape are failing on windows

lookup: mark node-sass and tape as flaky on windows

---

lib/lookup.json

Fixes: https://github.com/nodejs/citgm/issues/377
cc/ @richardlau

lookup: add "native" tag for native modules

---

README.md
lib/lookup.js
man/citgm.1
test/test-lookup.js

Currently we support resolving an npm tag, but not an npm version. Update to
handle both.
Could probably do with a test.

lib: support citgm module@version

---

lib/lookup.json

Currently failing on all platforms
ref: https://github.com/tapjs/spawn-wrap/issues/53

lookup: skip spawn-wrap

---

lib/lookup.json

spawn-wrap 1.3.6 fixes the npm-shrinkwrap.json error.
Refs: https://github.com/nodejs/citgm/pull/413
Refs: https://github.com/tapjs/spawn-wrap/issues/53

lookup: unskip spawn-wrap

---

.travis.yml

chore: update travis to include node 8

---

lib/lookup.json

they shipped code that doesn't work on v4

lookup: skip coffee-script for v4

---

lib/lookup.json

The test suites for these modules are not windows compatible
/cc @marijnh @ariya

lookup: disable acorn + esprima on windows

---

lib/lookup.json

Refs: https://github.com/libxmljs/libxmljs/issues/485
Refs: https://github.com/nodejs/citgm/issues/469

lookup: skip libxmljs on Node >=8

---

lib/lookup.json

lookup: skip ava on ppc and windows

---

lib/lookup.json

currently the install fails due to nsp + vulnerable modules
skip until this is fixed

lookup: skip yeoman

---

lib/lookup.json

all of these modules appear to fail due to filesystem related issues
* multer
* coffeescript
* mocha
* ava
/cc @sindresorhus @novemberborn @boneskull @GeoffreyBooth

lookup: skip modules failing on windows

---

lib/lookup.json

Lack of mocha support is generally due to support matrix of PhatomJS
* mocha
- aix
- rhel
- fedora
- ppc
- win32
* ava
- aix
- rhel
- ppc
- win32

lookup: skip modules on unsupported platforms

---

lib/lookup.json

Leveldb is now using destructuring which is not supported on 4.x

lookup: skip leveldb on <4

---

lib/lookup.json

It has a test to ensure snapshots are turned on

lookup: skip ava <4

---

lib/lookup.json

bug in traceur compiler polyfill in browserify is causing errors
in 8.x and above.
Willing to help fix this in browserify. Will open issue in repo when
I've had a bit more time to research
Refs: https://github.com/nodejs/node/pull/14888#issuecomment-328710065
/cc @substack

lookup: skip browserify in 8.x >

---

lib/lookup.json

#492 removed `level` from node 4 due to the use of destructuring. This was since fixed; the latest version of `level(up)` restores support of node 4 (Level/levelup#516).
@MylesBorins, cc @juliangruber @ralphtheninja @rvagg

lookup: restore level on 4

---

lib/common-args.js
package.json

Breaking changes:
- version() and help() are now enabled by default
- help command now only executes if it's the last positional in argv._
- Changes to unused "parse" method and "usage" second argument.

chore: update yargs

---

bin/citgm-all.js
lib/reporter/logger.js
lib/reporter/util.js
package.json
test/fixtures/reporter-fixtures.json
test/reporter/test-reporter-util.js

Skipped modules will now be logged and included in the report. Added `util.getSkipped` and some test cases. Closes #443

Report skipped modules

---

lib/lookup.json

Sodium Native now require bootstrapping a git submodule to work
Generally we would skip when there is a breakage, but this change
actively makes sodium-native no longer compatible with citgm
/cc @mafintosh @emilbayes

lookup: remove sodium-native

---

lib/lookup.js
test/test-lookup.js

If the package has been published from its git repository, npm adds a
`gitHead` property to the package.json file.
After this commit, the resolver will always use this if it is available
and then fallback to the git tag. This allows to run `citgm module`
with many modules without adding them to the lookup file and also
removes the need for the "prefix" option in most cases.

resolve: use package.gitHead if available

---

lib/lookup.json

As of ava 0.23.0 it is consistently failing in citgm on most enviroments
In ava 0.23.0 they have introduced a new dependency that limits the
number of cores used in CI. I believe that this is triggering a race
condition bug in npm 3.x and causing the suite to bail early.
Ava 0.22.0 is consistently passing with v6.x and v8.x is consistently passing
with npm 5.x
As such I think it makes sense to simply mark ava as flaky on versions of node
shipping with older versions of npm
Refs: https://github.com/avajs/ava/commit/3f81fc431016ca115177d2d79cf9db36b05f69ad
/cc @sindresorhus @novemberborn @nodejs/npm

lookup: mark ava as flaky on <8

---

lib/lookup.json

Test suite in mkdirp currently does not support these versions
Refs: https://github.com/substack/node-mkdirp/pull/139
/cc @substack we can remove these skips once the above PR lands

lookup: skip mkdirp on >= 8.x

---

lib/lookup.json

Test suite currently does not support the version of full-icu packaged
in Node.js 9.x
refs: https://github.com/unicode-org/full-icu-npm/issues/20
/cc @srl295

lookup: skip icu-full-test >= 9.x

---

lib/lookup.json

Currently unsupported platforms for the module. It appears there are
commits on master to fix this but seeing segfaults when testing locally
We can revert this when ffi is updated upstream
/cc @TooTallNate

lookup: skip ffi on >= 8.x

---

README.md
lib/lookup.js
lib/lookup.json

It is possible that a repo will not publish the commit that is found in
the gitHead field. One such example is the jQuery package.
This new field allows us to ignore the gitHead field on a per module
basis in the lookup.
This PR also sets `ignoreGitHead` for jquery

Add ignore githead field to lookup

---

lib/lookup.json

lookup: unskip level

---

lib/lookup.json

I have been seeing a failure on fips, suggesting that it should have failed:
```
not ok 65 - serialport v6.0.4 this module should have failed
```
Since `npm test` passes fine on fips, I suggest not expecting a failure.
<details><summary><code>npm test</code> pass</summary>
```
$ npm test
> serialport@6.0.4 test /home/alk/node-serialport
> istanbul cover ./node_modules/mocha/bin/_mocha
Transformation error; return original code
[Error: error:060A80A3:digital envelope routines:FIPS_DIGESTINIT:disabled for fips]
Transformation error; return original code
[Error: error:060A80A3:digital envelope routines:FIPS_DIGESTINIT:disabled for fips]
Transformation error; return original code
[Error: error:060A80A3:digital envelope routines:FIPS_DIGESTINIT:disabled for fips]
Transformation error; return …
```

lookup: serialport is not expected to fail on fips

---

lib/lookup.json

oh no!
fs-extra is busted on 8.x+ rn

lookup: skip fs-extra on >=8

---

package.json

4.x is currently breaking aix 😢
Refs: https://github.com/nodejs/citgm/issues/525
Alternative to: https://github.com/nodejs/citgm/pull/531

chore: roll back tar to 3.x

---

package.json

Fixes: https://github.com/nodejs/citgm/issues/525
Ran citgm on aix machine with a new version of tar and  got it to  pass.
```shell
$ ./bin/citgm.js express
info:    starting            | express             
info:    lookup              | express             
info:    lookup-found        | express             
info:    express lookup-replace| https://github.com/expressjs/express/archive/351396f971280ab79faddcf9782ea50f4e88358d.tar.gz
info:    express npm:        | Downloading project: https://github.com/expressjs/express/archive/351396f971280ab79faddcf9782ea50f4e88358d.tar.gz
info:    express npm:        | Project downloaded express-4.16.2.tgz
info:    express npm:        | npm install started 
info:    express npm:        | npm install successfully completed
info:    express npm: …
```

upgrade tar

---

lib/lookup.json

Both of those packages depend on older tap, which is broken on Windows (see https://github.com/tapjs/node-tap/issues/373). Skip those two packages on Windows, until tap version is updated.

lookup: skip sax and semver on win32

---

lib/lookup.json

The module is broken due removing the `noAssert` argument in
the Buffer module.
This disable running it for versions > 9. The maintainers got
contacted and an issue opened.

lookup: skip spdy-transport

---

bin/citgm-all.js
bin/citgm.js
lib/out.js
test/test-out.js

Pretty sure this was just a typo. 
Pretty sure this was just a typo. `--no-color` [is set in `lib/common-args.js`](https://github.com/nodejs/citgm/blob/8795c45ec0d192278ff612894718d7d10dea0a53/lib/common-args.js#L48) and camelCased by yargs.

lib: camelcase color variables

---

README.md
bin/citgm-all.js
lib/check-tags.js
test/bin/test-citgm-all.js
test/test-check-tags.js

Allows includeTags and excludeTags to be used with individual module
names.

Add module name to its tags

---

.eslintrc.yml

No need to have a capital letter for a consecutive comment.

fix: linter for consecutive comments 

---

lib/lookup.json

SPDY relies on spdy-transport and that broke due to a BC in 10.0.0.
However, neither of these modules are maintained anymore as they
got pretty much obsolete due to http2.
Refs: https://github.com/spdy-http2/spdy-transport/issues/52
Refs: #558

lookup: skip spdy on Node.js > 9

---

lib/lookup.json

This is some times showing up as failure. Since the test is inherently flaky (it is timers based without having any guarantee that the test works with e.g., heavy load) let us mark is as such.
It came up e.g. here: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/1418/nodes=aix61-ppc64/testReport/junit/(root)/citgm/thread_sleep_v2_0_0/
I also opened a PR to change the test but there is still no guarantee that it will work:
https://github.com/ForbesLindesay/thread-sleep/pull/17

lookup: mark thread-sleep flaky

---

lib/lookup.json

Only x64 systems are supported. This includes Windows.
See https://github.com/flowtype/flow-bin/blob/master/index.js (this is a peer dependency).

loopup: skip ava on all x86 systems

---

lib/lookup.json

jsonstream (500 weekly downloads) has been deprecated in favor of to
JSONStream (1m weekly downloads). The test framework still does not
work on Windows, so we keep the skip clause.

lookup: use JSONStream instead of jsonstream

---

lib/lookup.json

Fastify passes all hard requirements. As for soft requirements, it is
being added because of its HTTP2 support.
Ref: https://github.com/nodejs/node/issues/19453.
cc @delvedor

Add fastify to lookup.json

---

lib/lookup.json

sqlite3@4.0.1 has been released which supports Node v10 on Windows

lookup: unskip sqlite3

---

lib/lookup.json

Adding `true` to the skip array to skip on all platforms
and versions for right now. It appears that radium tests
are failing in CI due to infra related issues. No time to
dig in right now.

lookup: skip radium

---

lib/grab-project.js
package.json

Closes `stdin` and `stderr` when calling `npm pack`. This makes CITGM work with never `npm`.
Fixes: https://github.com/nodejs/citgm/issues/593

lib: fix npm pack

---

lib/lookup.json

`electron-prebuilt` is deprecated and has not had a version published in a couple years. It's flaky in CITGM, so let's remove it.
Would be great to get `electron` in there, but I'm guessing that's a lot of work?
/ping @codebytere

remove electron-prebuilt

---

lib/lookup.json

lookup: unmark ws as flaky on linux

---

lib/lookup.json

hey @jresig and @timmywil jQuery has been consistently flaky on OSX 10.10 and
10.11 in our CITM (smoke tests for node.js). Marking as flaky for now so it
doesn't cause our CI runs to be red.
Refs: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/1655/nodes=osx1010/testReport/(root)/citgm/jquery_v3_3_1/
Refs: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/1655/nodes=osx1011/testReport/(root)/citgm/jquery_v3_3_1/

lookup: mark flaky on OSX

---

lib/package-manager/install.js
lib/package-manager/test.js

On Windows use ';' as separator in PATH environment variable.

win: fix PATH env variable generation

---

lib/package-manager/test.js
lib/reporter/logger.js
lib/spawn.js

Fixes: https://github.com/nodejs/citgm/issues/618

lib: fix bug with huge test output

---

lib/lookup.json

Hard Requirements:
Soft Requirements:
Skipping Node 11 for now because a test uses `process.binding('timer_wrap')` (removed in 11).
/cc @sindresorhus

lookup: add got

---

lib/lookup.json

Hard Requirements:
Soft Requirements:

lookup: add debug

---

lib/package-manager/get-executable.js

It was breaking execution of npm sub-scripts because the
node_modules/npm/bin directory contains a npm.cmd file that would be
resolved from the PATH generated to run tests. However, npm doesn't
support being run from this directory.
Fixes: https://github.com/nodejs/citgm/issues/648

lib: do not resolve npm-cli.js on Windows

---

lib/lookup.json

Waiting for a new release that works on current Node.js version.
Refs: https://github.com/stylus/stylus/issues/2436

lookup: skip stylus on >=11

---

lib/lookup.json

Waiting for the fix to land and be in a release.
Refs: https://github.com/TooTallNate/node-time/pull/76

lookup: skip time on >=11

---

lib/lookup.json

They're using APIs that were removed from V8.

lookup: skip native modules that don't build on v12

---

lib/lookup.json

Some tests are broken by changes in the output of `console.log`. It's
not clear yet if this should be fixed in Node core or in the module's
tests.
Refs: https://github.com/nodejs/node/pull/23162#issuecomment-446716098

lookup: skip uglify-js on v12

---

lib/reporter/logger.js

This was currently breaking cntrl-c
Fixes: #663

logger: if !module.testOutput set to empty string

---

lib/lookup.json

Closes: https://github.com/nodejs/citgm/issues/524
Skipped on Windows because it the test scripts uses `sh`.

lookup: fix and enable pug

---

lib/lookup.json

We are currently skipping on >=8.x. Expanding to include 6.x as it
has been broken on the last two releases. We should dig in and see
if we can get this passing.
/cc @nzakas, @mysticatea, @not-an-aardvark

lookup: skip eslint

---

lib/lookup.json

lookup: skip ava on ia32

---

lib/lookup.json

The majority of these tests are failing because
`npm test` doest not appear to have the correct
path. Unsure if this is a CITGM bug, CI bug, npm
bug, or node bug... fun!

lookup: lots of windows skips

---

test/npm/test-npm-install.js

The checked error message differs between the version of npm included
in Node.js 11.10.0 compared to previous versions.
Fixes: https://github.com/nodejs/citgm/issues/680

test: fix test-npm-install for npm 6.7.0

---

lib/lookup.json

[node-report@2.2.2](https://github.com/nodejs/node-report/releases/tag/v2.2.2) fixes compilation on Windows.

lookup: unflake node-report on Windows

---

lib/match-conditions.js
test/test-match-conditions.js

This is a decent pattern to use when we need to temporarily skip a
module but don't want to lose the existing skip data for specific
platforms

lib: allow booleans in arrays for match conditions

---

lib/lookup.json

This is mostly to have a code base using Jest. It would be preferable to include Jest itself instead, but that is currently difficult due to some issues around colors.
See #684.
```sh-session
$ node -v
v12.0.0-nightly20190313e6fa50e953
$ node bin/citgm.js eslint-plugin-jest
info:    starting            | eslint-plugin-jest
warn:    update-available    | v4.0.0 (current: v3.4.8)
warn:                        | npm install -g citgm
info:    lookup              | eslint-plugin-jest
info:    lookup-found        | eslint-plugin-jest
info:    eslint-plugin-jest lookup-replace| https://github.com/jest-community/eslint-plugin-jest/archive/f6f6d84c1134bc3d1aff9c2715e97d309e185bc3.tar.gz
info:    eslint-plugin-jest npm:| Downloading project: …
```

lookup: add eslint-plugin-jest

---

README.md
lib/git-clone.js
lib/grab-project.js
lib/lookup.js
lib/lookup.json
lib/unpack.js
test/fixtures/custom-lookup-useGitClone.json
test/test-grab-project.js
test/test-lookup.js
test/test-unpack.js

If "useGitClone" is set to "true", a shallow clone of the
repository will be used instead of downloading the tarball.
Fixes: https://github.com/nodejs/citgm/issues/694

feat: add useGitClone option to lookup table

---

lib/lookup.json

ref is now unreliable on all versions of node
It appears it relies on `"mocha": *` which might explain what is going
on, but I am unable to reliable get the suite passing on 6, 8, or 10

lookup: skip ref

---

lib/reporter/junit.js
test/fixtures/parsed-junit.json
test/fixtures/reporter-fixtures.json
test/fixtures/test-out-xml-failing.txt
test/reporter/test-reporter-junit.js

Fixes reporting of skipped modules for the junit reporter.
Also tidy up the name for skipped modules, which do not have
`version` metadata.

reporter: fix junit skip reporting

---

lib/lookup.json

Refs: https://github.com/mapbox/node-sqlite3/issues/1138

lookup: skip sqlite on 12

---

lib/lookup.json

This reverts commit 37452aa0a5d4f7e5b09842f2c0dd4997d76e8e14.
Seems like something is failing again @agathver 

Revert "lookup: don't skip bcrypt for v12 (#685)"

---

lib/lookup.json

cheerio test failures have been fixed in cheerio@1.0.0-rc.3.
Fixes: https://github.com/nodejs/citgm/issues/699
This reverts commit 36d8dd28503f1b64f3eddcd2996178b2496d773e.

Revert "lookup: skip cheerio"

---

README.md
lib/lookup.js
lib/lookup.json
lib/package-manager/test.js
test/fixtures/custom-lookup-scripts.json
test/fixtures/omg-i-pass-with-scripts/build.js
test/fixtures/omg-i-pass-with-scripts/package.json
test/fixtures/omg-i-pass-with-scripts/test.js
test/npm/test-npm-test.js
test/test-lookup.js
test/yarn/test-yarn-test.js

If set, "scripts" specifies the scripts from the module's package.json
to run instead of the default "test".
Allows `nan` to be added (second commit).

feat: add scripts option to lookup table

---

lib/create-options.js
test/fixtures/omg-i-write-to-tmpdir/package.json
test/fixtures/omg-i-write-to-tmpdir/test.js
test/npm/test-npm-test.js
test/test-create-options.js
test/yarn/test-yarn-test.js

The test for some modules write into `os.tmpdir()` and do not always
clean up afterwards which can fill the temporary directory on our CI.
Redirect the temporary directory for modules being tested into CITGM's
`tmpDir` which gets removed at the end of the run.
Refs: https://github.com/nodejs/build/issues/1757

lib: redirect tmpdir for modules being tested

---

package.json

I didn't include this in the batch update because I thought they stopped supporting Node 6, but that's apparently [not the case](https://github.com/yargs/yargs/blob/master/CHANGELOG.md#1300-2019-02-02)

package: update yargs to 13.2.2

---

lib/check-tags.js

The log functions take two parameters: tag and message. Fix instances
of calling `log.info` with only one parameter (which is treated as tag).

lib: fix logging in lib/check-tags.js

---

lib/create-options.js
test/test-create-options.js

npm environment variables are prefixed with `npm_config_`.

lib: fix npm loglevel environment variable name

---

lib/citgm.js
test/test-citgm.js

* Remove outdated / wrong comments
* Add a "noname-" prefix if the module's name is a hash
* Stop emitting this.options. It is never used.

chore: cleanup citgm.js

---

.travis.yml

Needed to land https://github.com/nodejs/citgm/pull/709

chore(travis): stop supporting Node.js 6, add Node.js 12

---

lib/lookup.json

`serialport` now supports node 12. It has always supported windows32 (and it tested against it) so I’ve brought that back. I couldn’t find issues that explained why it was removed. The commit suggested that maybe it was flakey? If so I’d like to know more as we don’t see that in our tests.
Closes: https://github.com/node-serialport/node-serialport/issues/1742

chore: enable node 12 and win32 for serialport

---

lib/lookup.json

bcrypt v3.0.6 has been updated to use nan v2.13.2.
Refs: https://github.com/kelektiv/node.bcrypt.js/issues/715#issuecomment-484132851

lookup: unskip bcrypt for Node.js 12

---

README.md
bin/citgm.js
lib/lookup.js
test/test-lookup.js

First commit: also use --sha in case the module is not in the lookup table
Second commit: clarify that --sha can also be a branch or tag
For example to test the master branch of a module:
citgm moduleName --sha=master

Two --sha fixes

---

lib/lookup.json

They pass on my machine.
Do we have a way test 3 modules in one CI run? @richardlau

lookup: unskip bluebird, bson and radium

---

lib/lookup.json

lookup: unskip ws on win32

---

lib/lookup.json

The module is dead.
Previous attempt to fix its tests: https://github.com/mscdex/node-ftp/pull/191

lookup: remove ftp

---

lib/lookup.json

Bluebird v3.5.5 seems to pass on ppc and s390 for me locally and in ci 
https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-nobuild/641/nodes=rhel72-s390x/console
https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-nobuild/642/console
cc: @richardlau 

lookup: unskip bluebird on ppc and s390

---

lib/lookup.json

pug metadata on npm points to a URL we can't use. Override in
lookup.json.
Fixes: https://github.com/nodejs/citgm/issues/744

lookup: fix pug

---

lib/lookup.json

ember-cli@3.11.0 has failing tests. This means that CITGM fails across
all platforms for ember-cli. The issue is fixed in the ember-cli master
branch. It should be safe to use the master branch, as ember-cli
releases approximately every 6 weeks (coinciding with ember releases)
and is very conservative about changes that would require a semver bump
(again, as is ember--they share the same version number).

lookup: use master branch for ember-cli

---

lib/grab-project.js
test/test-grab-project.js

lib: show stderr when getting project from npm fails

---

lib/lookup.json

React's failing on ppc and s390. The issue seems to be that it tries to download electron and there are no pre-compiled binaries of electron for these platforms.
```
Error: GET https://github.com/electron/electron/releases/download/v5.0.9/electron-v5.0.9-linux-ppc64.zip returned 404
/home/iojs/tmp/citgm_tmp/490f84ce-553a-42cc-8633-20997dbe5f7d/react/node_modules/electron/install.js:49
throw err
^
Error: Failed to find Electron v5.0.9 for linux-ppc64 at https://github.com/electron/electron/releases/download/v5.0.9/electron-v5.0.9-linux-ppc64.zip
```
https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/

lookup: skip s390 and ppc for react

---

lib/create-options.js
lib/temp-directory.js
test/test-create-options.js

The tests for some modules write into `os.homedir()` and are not
cleaning up afterwards. This is accumulating over time on our CI
and require periodic manual cleaning.
Redirect the environment variables used by `os.homedir()` into
CITGM's temporary directory for the module being tested, which gets
removed at the end of the test run.
Refs: https://github.com/nodejs/build/issues/1908#issuecomment-544298898

lib: redirect homedir for modules being tested

---

bin/citgm-all.js
package.json
test/test-grab-project.js

* make-promises-safe@5.0.0 updated to 5.1.0
* tar@4.4.8 updated to 4.4.13
* yarn@1.16.0 updated to 1.19.1
* eslint-plugin-prettier@3.1.0 updated to 3.1.1
* xml2js@0.4.19 updated to 0.4.22
* update async@2.6.2 to 3.1.0
This is a breaking change. Code involving the drain property of the
queue objects had to be modified. See third bullet point under
https://github.com/caolan/async/blob/master/CHANGELOG.md#breaking-changes
* update bl@3.0.0 to 4.0.0
* update execa@1.0.0 to 3.2.0
This required updating the expected error message in a test, as execa
now provides more detail than it used to.
* update rimraf@2.6.3 to 3.0.0
* update supports-color@6.1.0 to 7.1.0
*  update tar@4.4.13 to 5.0.3
* update which@1.3.1 to 2.0.1
* update yargs@13.3.0 to 14.2.0
Closes: …

chore: update dependencies

---

lib/grab-module-data.js
test/test-grab-module-data.js

Use the latest satisfying version returned by npm.
Throw an error if nothing matches.
Fixes: https://github.com/nodejs/citgm/issues/762

fix: support lookup with semver ranges

---

lib/spawn.js
test/test-grab-project.js

fix: escape carets on Windows cmd arguments

---

lib/timeout.js
test/npm/test-npm-install.js
test/npm/test-npm-test.js
test/test-timeout.js
test/yarn/test-yarn-install.js
test/yarn/test-yarn-test.js

Refs: https://github.com/nodejs/citgm/pull/728#issuecomment-548698680

fix: don't mark module as flaky on time outs

---

lib/lookup.json

* Skip zeromq
- cmake not on buildbots
* skip node-gyp
- new test fails on new releases
* set commander as flaky
- timeouts on our infra

Update lookup dec 2019

---

lib/lookup.json

Set the `FAST_TEST` environment variable to skip the headers download
test.
Fixes: https://github.com/nodejs/node-gyp/issues/2000
With `-v silly` I get the following with a fake Node.js v13.6.0 (v13.5.0 with the minor version bumped):
```console
verbose: node-gyp npm-test:  | # Subtest: download headers (actual)
verbose: node-gyp npm-test:  | ok 1 - Skipping acutal download of headers due to test environment configuration # SKIP
verbose: node-gyp npm-test:  | 1..1
verbose: node-gyp npm-test:  | # skip: 1
verbose: node-gyp npm-test:  | ok 5 - download headers (actual) # time=2.199ms
```
cc @MylesBorins 

lookup: unskip node-gyp

---

lib/lookup.json

Running `resolve`'s tests will help avoid problems like https://github.com/nodejs/node/pull/30963 from occurring silently.
Hard Requirements
Soft Requirements
At least one of:
Tests currently fail on v13.4 due to https://github.com/nodejs/node/pull/30963 not being included in it; the next release of resolve will fix that.

lookup: add `resolve`

---

.github/workflows/nodejs.yml

Since Node.js 8 is now EOL (as of December 31st, 2019), this PR proposes the removal of Node.js v8 from the GitHub Actions CI.

ci: remove Node.js 8 from CI suite

---

lib/lookup.json

See #779
Using this PR to kick off a test run to see if CITGM on AIX gets further when this module is skipped.

lookup: skip clinic on AIX and Windows

---

lib/lookup.json

AVA@3 tests should no longer be flaky. We've also removed some tight coupling with Node.js versions, so overall it should be more reliable.
I'm not sure what all the skipped values are, but I'm intending to re-enable tests in Node.js 10 and above, as well as 64-bit Windows.

Re-enable AVA

---

lib/lookup.json

To make citgm testing faster, mark the flaky tests as 'skip' until the flaky tests can be fixed. Marking them as 'skip' (instead of removing) will keep the modules around to be eventually added back to the test suite.
- async
- commander
- node-sass
- request
- vinyl-fs
Discussed with @BethGriggs and @MylesBorins, and we decided this would be a good first step towards remediating some of the flaky test suites.

lookup: remove "flaky" and add "skip" to flaky modules

---

lib/lookup.json

ava still fails everywhere reverting the change to enable it
https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/2306/testReport/

Revert "Re-enable AVA (#781)"

---

.github/workflows/nodejs.yml

- Use actions/checkout@v2
- Upload coverage report now that Codecov supports tokenless uploads

ci: update GitHub action

---

lib/lookup.json

`bson` currently failing on all platforms
failing since v1.1.4 was published 6 hours a go.

lookup: skip bson on all platforms

---

lib/lookup.json

Got seems to be failing on all Node.js versions across all platforms with:
<details>
got@10.6.0 test /Users/bethgriggs/got
xo && tsc --noEmit && nyc ava
`parseForESLint` from parser `@typescript-eslint/parser` is invalid and will just be ignored
source/normalize-arguments.ts:46:1
⚠   46:1   Unexpected todo comment.                                                                                    no-warning-comments
⚠   47:38  Arrow function has a complexity of 49. Maximum allowed is 20.                                               complexity
⚠  320:2   Unexpected todo comment.                                                                                    no-warning-comments
⚠  375:42  Async arrow function has a complexity of 57. Maximum allowed is 20. …

lookup: mark got as skip on all versions

---

.travis.yml
README.md

We currently have a full test matrix via github actions which tends to
be more reliable / stable than the travis CI build. Is there a reason
we are keeping support for travis at this point?

build: remove travis

---

lib/lookup.json

removes darwin from flaky platform of readable-stream (https://github.com/nodejs/citgm/issues/787)

remove darwin as flaky from module readable-stream

---

lib/lookup.json

Examples seen here
https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/2328/testReport/
Already flaky on a couple of other platforms. Tested locally and had inconsistent results.

lookup: mark winston flaky on darwin

---

README.md
lib/lookup.json
lib/package-manager/install.js
test/npm/test-npm-install.js

For #728 so we can skip the TypeScript compilation. Seems like only a single module used the option anyways, so I just changed its meaning. Not sure if that's considered a breaking change?

feat: allow overriding install command

---

README.md
bin/citgm-all.js
bin/citgm.js
lib/common-args.js
lib/grab-project.js
lib/lookup.js
lib/package-manager/install.js
lib/package-manager/test.js
lib/timeout.js
test/npm/test-npm-install.js
test/npm/test-npm-test.js
test/test-grab-project.js
test/test-timeout.js
test/yarn/test-yarn-install.js
test/yarn/test-yarn-test.js

This is #740 without the changes to lookups. I have the same question @Zirro had over there though - where to add tests? Seems like a bunch of the options you can define in `lookup.json` are untested.

feat: add timeout option for both install and test phase

---

lib/lookup.json

Adds the pino logger. It currently has 2 mln downloads/month, and it's probably worthwhile to check it before release of Node.
Note that it currently does not pass on Windows with v14, likely due to https://github.com/nodejs/node/issues/33166 or some other regression. See https://github.com/pinojs/pino/pull/839 for some details.

Added pino

---

lib/lookup.json

Use a different npm script to avoid browser tests for through2 and sort
the keys for the through2 entry in lookup.json.
Fixes: https://github.com/nodejs/citgm/issues/809

lookup: avoid browser testing for through2

---

lib/package-manager/test.js
test/fixtures/omg-i-have-no-test-script/package.json
test/npm/test-npm-test.js
test/yarn/test-yarn-test.js

Some modules do not call their test script `test`. For example, a
module using [Yarn workspaces](https://yarnpkg.com/advanced/qa#how-to-share-scripts-between-workspaces) may define `workspace:test` as their
testing script. We can specify the script to run in our `lookup.json`
but there was a place in our code that was specifically looking for
a script called `test`.

lib: allow modules without a script called `test`

---

lib/lookup.json

Both are currently consistently flaky

update lookup for v14.x known failures

---

lib/lookup.json

Currently tracking down failures on v14.x and uncovered that `gulp`
is relying on an out of date / unsupported version of `chokidar`
which is itself relying on an out of date version of `fsevents`.
The file watching dependency `glob-watcher` is currently broken
on both 12.x and 14.x due to this. While the tests may pass on
some platforms I think it may be prudent to skip gulp altogether
on darwin platforms until they have fixed their dependency issues.

lookup: skip gulp on darwin

---

lib/lookup.json

This reverts commit 24acf67c2b6ed3dce7157215998ce576a2c82650.
Shot will now pass on 14.x

Revert "lookup: skip shot on v14.x"

---

lib/lookup.json

Watchify relies on an old version of chokidar which has an old version
of fsevents, which doesn't support Node.js 12.x+
Skipping on MacOS until this is fixed upstream

lookup: skip watchify on darwin

---

lib/package-manager/install.js

This can speed up install time by a non-trivial amount.

npm-install: use --no-audit and --no-fund by default

---

lib/lookup.json

debug just made it's first release in 2 years and now uses headless
chrome for testing. We can no longer use the default test script due
to this. Manually run a subset of the tests that we can support.

lookup: specify scripts for debug

---

lib/citgm.js
test/fixtures/omg-i-timeout/package.json
test/fixtures/omg-i-timeout/test.js
test/test-citgm-timeout.js

Previously any errors occurring when removing the temporary directory
during cleanup after a test were not caught and resulted in the `end`
event not being emitted. For `citgm-all` this prevented moving onto
the next module to test.
Refs: https://github.com/nodejs/citgm/issues/802

lib: handle temporary directory removal errors

---

lib/lookup.json

eslint-plugin-jest uses yarn policies which uses emscripten which
only supports little endian architectures.
Refs: https://github.com/nodejs/citgm/issues/824#issuecomment-699470974

lookup: skip eslint-plugin-jest on big endian platforms

---

lib/lookup.json

`is-core-module` is the extracted "is core module" logic used by `resolve`

lookup: add `is-core-module`

---

lib/create-options.js
lib/lookup.json
lib/package-manager/install.js
test/test-create-options.js

yarn v2 doesn't support the `YARN_IGNORE_ENGINES` environment variable.
We still need to set `YARN_IGNORE_ENGINES` for older versions of yarn
to allow installation with unreleased versions of Node.js. Projects are
able to use yarn policies to set the version of yarn they are using,
so we need to version sniff to determine whether or not to set the
environment variable.
Fixes: https://github.com/nodejs/citgm/issues/824

fix: don't ignore engines with yarn v2+

---

lib/lookup.json

radium ships with a yarn.lock file and they use yarn to install
and run their test suite in CI. Seems appropriate to use yarn
for this project in CITGM.

lookup: use yarn for radium

---

lib/lookup.json

The 3.0.1 release has a broken test suite.
Refs: https://github.com/socketio/socket.io/commit/e69d0ad6020828e9811f8a71b614e97f12131603

lookup: use master for socket.io

---

lib/lookup.json

The latest release depends on a broken version of the workerpool module
for its test runner.

lookup: use master for cheerio

---

lib/lookup.json

Adds end-of-stream and pump to CITGM.
Some minor releases in Node 10 broke both so it would have been good to have caught that early instead :)

add end-of-stream and pump

---

.github/workflows/nodejs.yml
.github/workflows/test-module.yml

Form:
Example run on my fork with `lodash` module: https://github.com/targos/citgm/actions/runs/623994089
Another example with:
- module: https-proxy-agent
- repository: lpinca/citgm
- ref: add/https-proxy-agent
https://github.com/targos/citgm/actions/runs/624006145

ci: add a GitHub workflow to test a module with CITGM

---

lib/grab-project.js
lib/lookup.json

We've had a release, so in theory the color issue should be solved. We've sped up our own CI by skipping the TypeScript build, should probably make the same change here. For now I just thread through a way higher timeout.
I haven't run this locally, I just figured I'd open up the PR before being computerless for the weekend. 🤞 
Fixes #684

chore: add jest to lookup

---

lib/lookup.json

This was, surprisingly, not in this list. Also, I am not sure, but I *guess* this shouldn’t be merged as long as `npm` is broken on node `master`?

lookup: add npm

---

lib/lookup.json

It depends on `Object.fromEntries` which doesn't exist in that version.

lookup: skip yeoman-generator on v10.x

---

README.md
lib/lookup.js
lib/lookup.json
test/fixtures/custom-lookup-log.json
test/test-lookup.js

Patch the lookup object in memory for backwards-compatibility.

lookup: deprecate and rename "master" field to "head"

---

lib/lookup.json

Once this is green we can land it (needs a CI run first).

lookup: add hapi

---

lib/lookup.json

node-report has traditionally only supported LTS releases and is
planned to be archived once Node.js 10 goes End-of-Life and all
remaining in support versions of Node.js have the diagnostic report
feature.
Refs: https://github.com/nodejs/node-report/issues/142

lookup: skip node-report on Node.js 15.x and later

---

test/bin/test-citgm-all.js

Previously, the functions pkgInstall and pkgTest are missing
code coverage for the lines involving yarn. The test added
now checks these lines by passing in the -y argument when
calling spawn. This does not test when the package doesn't include
the tests, forcing citgm to grab the tarball from github.
Writing such a test would involve setting the property
useYarn.

Provide missing code coverage in tests in package-manager

---

lib/lookup.json

0249f2c62e40e4c914faa31fc82763e7cbea092a included an errant ":" in the
"skip" key.

lookup: fix skip for node-report

---

.github/workflows/nodejs.yml
.github/workflows/test-module.yml

10 is EOL, and 16 is new and shiny? 😀 
Possibly blocked by #852?

chore: test using node 16, remove node 10

---

lib/lookup.json

Fixes #860
@siimon @zbjornson do you want to not be included here?
Note that `16.x` on GH Actions will fail: https://github.com/siimon/prom-client/pull/436#issuecomment-832452127

add prom-client to lookup

---

lib/lookup.json

PPC segfaults all seem related to the TypeScript compiler.
- use HEAD for "nan" (test fixes not in a release)
- use HEAD for "yargs" (lint fixes not in a release)
- commander errors on AIX and segfaults on PPC
- cheerio times out on AIX
- npm errors on AIX
- socket.io fails in a V8 CHECK on AIX and segfaults on PPC
- esprima fails on AIX and segfault on PPC
- path-to-regexp segfaults on PPC
- ws fails in a V8 CHECK on PPC
- glob fails everywhere, including their own CI on Travis
- jest fails everywhere because MongoDB cannot start
- debug fails everywhere, including their own CI on Travis

lookup: skip permanent failures

---

lib/lookup.json

If I'm reading the test correctly, it looks like the test expects this: https://github.com/ForbesLindesay/thread-sleep/blob/master/index.js#L10-L30, to run a specified amount of time according to this test: https://github.com/ForbesLindesay/thread-sleep/blob/master/test.js#L37. We're seeing the test flake because the time returned doesn't always pass the assertion. (ie. https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/2707/nodes=win-vs2019/testReport/junit/(root)/citgm/thread_sleep_v2_2_0/)

lookup: mark thread-sleep as flaky

---

lib/lookup.json

See https://github.com/nodejs/citgm/pull/867#issuecomment-860657374

chore(jest): remove examples before running tests

---

README.md

The correct attribute to strip out ANSI data is `stripAnsi`.

doc: correct `stripAnsi` attribute

---

lib/lookup.json

https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-nobuild/1121/nodes=rhel7-s390x/testReport/junit/(root)/citgm/blake2b_wasm_v2_4_0/
https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-nobuild/1121/nodes=aix72-ppc64/testReport/junit/(root)/citgm/blake2b_wasm_v2_4_0/

lookup: skip `blake2b-wasm` on `aix` and `s390`

---

lib/lookup.json

https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-nobuild/1121/nodes=rhel7-s390x/testReport/junit/(root)/citgm/cheerio_v1_0_0_rc_10/

lookup: skip `cheerio` on `s390`

---

.github/ISSUE_TEMPLATE.md

( `-v` is mapped to `--verbose` not `--version`)

meta: fix command in issue template

---

lib/lookup.json

Cheerio currently fails on all platforms (refs: https://ci.nodejs.org/job/citgm-smoker-nobuild/1184/console):
```
> cheerio@1.0.0-rc.10 prepare
> husky install
husky - Git hooks installed
added 583 packages in 15s
> cheerio@1.0.0-rc.10 test
> npm run lint && npm run test:jest
> cheerio@1.0.0-rc.10 lint
> npm run lint:es && npm run lint:prettier
> cheerio@1.0.0-rc.10 lint:es
> eslint --ignore-path .gitignore .
/home/iojs/tmp/citgm_tmp/1433aa07-54bb-4025-9179-f8c17b9ca201/cheerio/benchmark/suite.ts
43:28  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
50:41  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
54:28  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
58:60  warning …
```

lookup: only run tests for cheerio

---

lib/lookup.json

Adds `tough-cookie` (42 million weekly downloads) to `lookup.json`.
`npm install && npm test` or (`yarn install && yarn test`) using the tarball
downloaded from the Github tag mentioned above

lookup: add tough-cookie

---

lib/lookup.json

This package has ~6 million weekly downloads and we broke it in
Node.js 10.0.0
Refs: https://github.com/nodejs/node/issues/24474#issuecomment-511963799

lookup: add https-proxy-agent

---

lib/lookup.json

The module `david` has been skipped for 4 years in CITGM, has minimal
downloads, and no longer appears to be actively maintained.

lookup: remove david

---

lib/lookup.json

Unskip and use `head` for `weak` instead of the last published
version from six years ago.
CI: https://ci.nodejs.org/job/citgm-smoker-pipeline/164/

lookup: use head for weak

---

lib/lookup.json

Clinic.js is now outside of `@nearform` scope package.

lookup: update clinicjs package scope

---

lib/lookup.json

The module `node-report` is deprecated on npm and only has 1,500
downloads per week.
----
My gut feel is that we're probably not getting the value from including this module with it having low downloads, being deprecated, and skipped on all supported versions apart from Node.js 14.

lookup: remove node-report

---

lib/lookup.json

From CITGM Smoker Pipeline runs, this module appears to now only fail on
Windows.
----
Runs - https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-pipeline/168

lookup: only skip mkdirp on win32

---

lib/lookup.json

* It fails in the majority of the platforms architectures.
* No commit on their github repo since January 2019.
* Current npm downloads ~5.000/per week.
* No activity on the github issues, with 218 issues open. 
* Last issue resolved was on 14 Dec 2020

lookup(ffi): remove ffi from citgm lookup.json

---

lib/lookup.json

`path-to-regexp` tests no longer fail on Node.js 18 and later.
---
CI: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-pipeline/177/
Tests still fail on AIX, so it remains skipped on that platform only.

lookup: unskip path-to-regexp for Node.js 18

---

lib/lookup.json

semver's test suite is passing but a later failing post script results
in it being reported as a failure.
---- 
* Node.js 18 - https://ci.nodejs.org/job/citgm-smoker-nobuild/1315
* only failure is #917

lookup: set ignore scripts for semver

---

lib/lookup.json

Tested running on Node 14, 16 and 18 in ppc, s390 and x64_86 architectures. It fails only on node 14 in s390x

lookup(express-session): remove skipping node 16 version and above 

---

lib/grab-module-data.js

npm 7 and higher now have an exit code for failed fetches. This introduces a subtle behavior change in testing as the error cases are slightly different. This tiny change to `grab-module-data.js` adds a regex to ensure a consistent code path is followed across all maintained versions of npm.
TBH there is likely a cleaner way to fix this, but it would involve a lot more refactoring which could create other unexpected bugs.
This should fix the broken CITGM test suite

grab-module-data: fix broken test

---

lib/lookup.json

minmist: remove as GitHub repo no longer exists
radium: remove as package is deprecated
pino: skip as current ref head doesn't exist on GitHub
yargs: skip as current release is broken by TS update

lookup: remove and skip packages currently failing

---

lib/lookup.json

adds [`jose`](https://www.npmjs.com/package/jose)
It covers the `node:crypto`, and `Web Cryptography API` modules.

lookup: add jose

---

lib/lookup.json

This PR un-skips blake2b-wasm for s390x system architecture, after the recent upgrade of esbuild on wasm-tools (which is a dependency on blake2b-wasm). There is an open PR on blake2b-wasm for upgrading wasm-tools https://github.com/mafintosh/blake2b-wasm/pull/21 although we dont have to wait for the PR to land, due to npm resolves wasm-tools, during blake2b-wasm npm install, from 0.2.0 to 0.2.1

un-skipping blake2b-wasm on s390x

---

lib/grab-module-data.js

The way npm 9 errors for non-existent module versions differs from previous versions. Adding an extra regex to check for that case and use the correct erroring code path internally.

lib: fix edge case for npm 9

---

package.json

This is currently imported in the test suite. It is only a transitive dependency right now. Installing as dev-dep to avoid issues with availability in the future.

deps: add ansi-regex as devdep

---

lib/bin/citgm-all.js

I am running the `citgm` locally in a custom Node.js build and I got the following error:
```
...
error: done                | The smoke test has failed.
TypeError [ERR_INVALID_ARG_TYPE]: The "code" argument must be of type number. Received type boolean (true)
at process.set [as exitCode] (node:internal/bootstrap/node:128:9)
at process.exit (node:internal/process/per_thread:187:24)
at done (file:///home/rafaelgss/repos/os/citgm/lib/bin/citgm-all.js:220:13)
at /home/rafaelgss/repos/os/citgm/node_modules/async/dist/async.js:1496:46
at Array.forEach (<anonymous>)
at trigger (/home/rafaelgss/repos/os/citgm/node_modules/async/dist/async.js:1496:27)
at /home/rafaelgss/repos/os/citgm/node_modules/async/dist/async.js:1569:21
at /home/rafaelgss/repos/os/citgm/node_modules/async/dist/async.js:327:20 …
```

fix: parse boolean to number

---

package.json

Dependabot can't do this because we don't have a package-lock.json.

chore: bump xml2js to 0.5.0

---

lib/lookup.json

Ref: https://github.com/nodejs/TSC/issues/1397
I believe all the [requirements](https://github.com/nodejs/citgm/blob/main/CONTRIBUTING.md#submitting-a-module-to-citgm) are met. [The module has 1,778,787 weekly downloads on npm](https://www.npmjs.com/package/import-in-the-middle) and uses loaders, which AFAIK no others in `lookup.json` do.

lookup: add import-in-the-middle

---

lib/lookup.json
test/test-lookup.js

Remove all modules that failed the latest 20.x release run. We need to be able to trust that a failed CITGM run is something that needs to be investigated.

lookup: declare bankruptcy on flaky modules

---

lib/lookup.json

Ref: https://github.com/nodejs/citgm/pull/959#issuecomment-1712344481

lookup: remove acorn from test suite

---

lib/lookup.json

From looking at the results of runs 3220-3228, `prom-client` only fails on Windows. I'd like to first try and see if using `head` works (as we've upgraded the version of Jest used there).
If this doesn't work, I guess we can skip Windows platform instead.

fix: use `head` of `prom-client`

---

lib/lookup.json

Ref #959.
I've gone through CITGM smoker builds from 3220 to 3228 (at the time of writing, the last completed run) and checked them all for failures with Jest.
- [3220](https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/3220/)
- due to `punycode` deprecation, which will be fixed when we upgrade JSDOM to the latest (this is a breaking change, but I'll start landing those this weekend or next week)
- There's also a [no space left on device](https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/3220/nodes=ubuntu1804-64/testReport/junit/(root)/citgm/jest_v29_6_2/) error. Extra weird here is that it uses 29.6.2, instead of 29.6.4
- [3221](https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/3221/)
- Timed out on …

fix: get Jest green

---

lib/lookup.json

The clone for leveldown is not working. Pinning to "head" fixes it.

lookup: fix leveldown

---

lib/lookup.json

Leveldown package fails on s390x and on ppc systems, therefore it should be as skipped.

Moving leveldown from flaky to skip on ppc and s390 systems

---

lib/lookup.json

lookup: fix entries for underscore, dicer, and csv-parser

---

lib/lookup.json

This skips the remaining platforms that still pose a problem for verifying serialport against a `-pre` version of Node.js
Relates to: [#992](https://github.com/nodejs/citgm/pull/992)

lookup: skip platforms for serialport

---

lib/lookup.json

In 2 cases in the recent builds ava failed due to timeouts. This PR increase the ava timeout to **10 minutes**.
This is the issue reported: 
```
153 tests passed
11 tests remained pending after a timeout
```
Reference to the issues: 
- https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/3302/nodes=fedora-last-latest-x64/testReport/junit/(root)/citgm/ava_v5_3_1/
- https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/3297/nodes=fedora-last-latest-x64/testReport/junit/(root)/citgm/ava_v5_3_1/
I'm not sure if this is a proper solution. As an alternative, we can set the module as flaky.
@sindresorhus @novemberborn I'm tagging you since you are listed as the package maintainers, maybe you have more info about how we …

chore: increasing timeout for ava

---

lib/lookup.json

Removing `torrent-stream` from lib/lookup.json since it has been failing
regularly on both `v18.x` and `v20.x` release lines due to a timeout.
Refs: https://github.com/nodejs/citgm/issues/1000

chore: remove torrent-stream

---

lib/lookup.json

Based on the discussion at #996 
Link to the testReport failure: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/3310/testReport/
Please before approving/merging, check that the skipped platforms are the one related to the testReport, I'm still not 100%

chore: skip nan on some platforms

---

test/npm/test-npm-install.js
test/npm/test-npm-test.js
test/reporter/test-reporter-junit.js
test/reporter/test-reporter-tap.js
test/test-grab-project.js
test/test-timeout.js
test/yarn/test-yarn-install.js
test/yarn/test-yarn-test.js

I was getting errors on my machine because multiple tests were creating sandboxes with the same name, because `citgm-${Date.now()}` wasn’t unique enough.

test: avoid colliding sandboxes

---

lib/lookup.json

We merged #905 without running the full suite of integration tests to make sure that we were testing at least *something*. This PR aims to enable a couple of the most important integration tests (still not all of them).

Adds integration tests for Yarn

---

CONTRIBUTING.md
README.md
lib/bin/citgm-all.js
lib/bin/citgm.js
lib/citgm.js
lib/common-args.js
lib/grab-project.js
lib/lookup.js
lib/package-manager/get-executable.js
lib/package-manager/index.js
lib/package-manager/install.js
lib/package-manager/test.js
package.json
test/bin/test-citgm-all.js
test/helpers/make-context.js
test/pnpm/test-pnpm-install.js
test/pnpm/test-pnpm-test.js

This adds support for `pnpm` like we have for Yarn, resolving #1017. It also adds `pnpm` itself to the list of packages to test, though I don’t know if it will pass in all our environments. That’s the second commit and can be excluded if we want.

feat: add pnpm as optional package manager

---

lib/citgm.js
lib/lookup.js
lib/package-manager/test.js
lib/reporter/logger.js

The main motivation here is to fix misleading version output when using the `-c` option.
```console
$ npx citgm -v verbose -c 37c34bad omg-i-pass 
info: starting            | omg-i-pass          
verbose: omg-i-pass using-uid| 501                 
verbose: omg-i-pass using-gid| 20                  
verbose: omg-i-pass using-node| /Users/bgriggs/.nvm/versions/node/v20.9.0/bin/node
verbose: omg-i-pass mk.tempdir| /var/folders/9g/93qrln9j5yq3396zcjzsghf00000gn/T/11c4180e-ff8e-4b33-8641-5dfa4dc76c80
verbose: omg-i-pass npm-view | Retrieving Meta Data
verbose: omg-i-pass npm-view | Data retrieved      
info: lookup              | omg-i-pass          
info: lookup-notfound     | omg-i-pass          
info: lookup-githead      | https://github.com/TheAlphaNerd/omg-i-pass/archive/37c34bad.tar.gz …
```

lib: log correct version and sha for -c option

---

lib/lookup.json

Underscore package is no longer flaky and it passes on s390x systems, so its good adding it for increasing the Node.js test coverage.

Un-flakying underscore package on s390x as is no longer flaky

---

lib/lookup.json

Level package fails on s390x, therefore it should be as skipped.

Moving level package from flaky to skip

---

lib/lookup.json

Underscore is constantly failing on Node.js v18.x:
- https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/3310/nodes=osx1015/testReport/(root)/citgm/underscore_v1_13_6/
- https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/3309/nodes=osx1015/testReport/(root)/citgm/underscore_v1_13_6/
- https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/3300/nodes=osx1015/testReport/(root)/citgm/underscore_v1_13_6/
This PR will disable underscore for now. 
@jashkenas you are listed as the maintainer of this package, can you please take a look at the issue and evaluate if is a legitimate issue or a false positive from citgm that we can fix? :) 
By running `citgm underscore` I'm currently not able to reproduce the issue on …

chore: disable underscore on macOS

---

lib/lookup.json

Ref: https://github.com/nodejs/citgm/issues/1033
Pinging module authors again: 
* @stefanpenner, @rwjblue, @Turbo87, @kellyselden
* @kriskowal
* @SBoudrias, @sindresorhus

lib: skip flaky modules on v21

---

lib/lookup.json

Following up on the recent bankruptcy of the CITGM, this PR removes all modules that are being skipped by either having a "skip: true" or because we're skipping all active release lines, for instance: ">= 17" or ">= 16". I know that the idea of "skip: true" was temporary, but some modules have been skipped for quite some time.
My suggestion for the modules that still want to be included in the current CITGM is to open a new PR to add it back so we guarantee our CITGM will not be red/failing until issues are fixed - please note a flaky CITGM affects directly the efforts of a release.
Before pinging module authors I'd like to get @nodejs/tsc approval since the list is big and I don't want to cause any more noise in their notification box.

lib: drop skipped modules

---

lib/lookup.json

In an effort to tidy up the skip/flaky tags.

lookup: remove EOL versions from lookup.json

---

lib/lookup.json

Re-enable readable-stream

---

lib/lookup.json

The condition was added in 861b02bc260a but it is not clear why. Maybe the tests pass now.

lookup: unskip bufferutil on win32

---

lib/lookup.json

lookup: re-add undici

---

lib/citgm.js
lib/utils.js
test/test-lookup.js

Convert `fetchSpec` to "latest" when it's "*" to accomodate for
the breaking change that happened in version 10 of the library.
Make lookup tests closer to reality by using the package arg parser
there and constructing fake module metadata that look more like
what the npm API returns.
Refs: https://github.com/nodejs/citgm/pull/628
Refs: https://github.com/npm/npm-package-arg/releases/tag/v10.0.0

lookup: fix handling of npm-package-arg result

---

lib/lookup.json

Work in progress because babel is still not compatible with citgm. This is what you have to do now to test it:
```
make bootstrap
make test
```

lookup: add babel

---

lib/lookup.json

There was no release in almost two years, but tests were fixed recently.
Refs:  https://github.com/hapijs/shot/commit/2dca4110dfa75c844479b2e0c74f0153379fa6bf

lookup: use head for `@hapi/shot`

---

lib/lookup.json

The module is not maintained anymore and fails on Node.js >=22 because
its test suite uses the `esm` module (abandoned and broken).

lookup: do not use head for `csv-parser`

---

lib/temp-directory.js

On macOS, `os.tmpdir()` returns a path that contains a symbolic links.
This can cause issues with modules that expect the environment to only
contain real paths. For example, the `resolve` module uses the HOME env
variable, which is derived from the context's path.
<details>
<summary>
Example of fixed error:
</summary>
```
error: error:              | not ok 450 sanity check: require.resolve finds HNM `baz`
error:                     | ---
error:                     | operator: equal
error:                     | expected: |-
error:                     | '/var/folders/9n/05y6s4ls78515vmnbd86hktm0000gn/T/fc57c0d4-4128-4194-8fb0-f862577957ef/home/.node_modules/baz/quux.js'
error:                     | actual: |-
error:                     | …
```

fix: resolve symlinks for test context's path

---

lib/lookup.json

Run it with `--ignore-scripts` so it doesn't try to install Puppeteer.

lookup: fix npm install for `through2`

---

lib/lookup.json

The on-finished module is added, and it doesn't show any failures locally.
Fixed: #803

lookup: on-finished

---

lib/temp-directory.js
test/test-temp-directory.js

Refs: https://github.com/nodejs/node/pull/57005#issuecomment-2666921592

lib: reduce the length of the temporary directory path

---

lib/lookup.json

Updates the jose CITGM lookup section
- esbuild is no longer used during testing
- versions before 20.x are no longer supported
- skip win32 because the test scripts aren't compatible with windows
[both test scripts passing in jose's CI on 20, 22, and current](https://github.com/panva/jose/actions/runs/13477997120).

lookup: update jose

---

lib/lookup.json

We need https://github.com/expressjs/session/commit/67d61ee1799a8070dff4a5b759189be2023c7a62 until their next release.

lookup: use HEAD for `express-session`

---

.github/workflows/close-stalled.yml
.github/workflows/nodejs.yml
.github/workflows/test-module.yml
package.json
test/reporter/test-reporter-junit.js
test/reporter/test-reporter-tap.js

- **chore: update GitHub action versions**
- **chore: update supported Node.js versions**
- **test: remove custom assertion messages in reporter tests**

Update workflows and supported Node.js versions
